stages:
  - build
  # - test
  - deploy

default:
  tags:
    - Dind

image: docker:19.03.12

services:
  - docker:19.03.12-dind

build-docker-image:
  stage: build
  script:
    - docker build -t agent-training-academy-ui:build .

# test-code-with-coverage:
#   image: node:16.13.2
#   stage: test
#   script:
#     - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#     - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#     - apt-get update && apt-get install -y google-chrome-stable
#     - npm install --force
#     - npm run test:ci
#   artifacts:
#     paths:
#       - coverage/

deploy-dev:
  stage: deploy
  script:
    - apk add --update curl
    - echo $NEXUS_PASS | docker login docker.aws.ccit.ops.charter.com --username $NEXUS_USER --password-stdin
    - docker build -t docker.aws.ccit.ops.charter.com/ata/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA .
    - docker push docker.aws.ccit.ops.charter.com/ata/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA
    - docker tag docker.aws.ccit.ops.charter.com/ata/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA docker.aws.ccit.ops.charter.com/ata/agent-training-academy-ui:dev
    - docker push docker.aws.ccit.ops.charter.com/ata/agent-training-academy-ui:dev
  only:
    - development
    - release*
    - main

deploy-qa:
  stage: deploy
  script:
    - apk add --update curl
    - echo $NEXUS_PASS | docker login docker.aws.ccit.ops.charter.com --username $NEXUS_USER --password-stdin
    - docker pull docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA
    - docker tag docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:test
    - docker push docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:test
  only:
    - release*
    - master
  when: manual

deploy-prod:
  stage: deploy
  script:
    - apk add --update curl
    - echo $NEXUS_PASS | docker login docker.aws.ccit.ops.charter.com --username $NEXUS_USER --password-stdin
    - docker pull docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA
    - docker tag docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:$CI_COMMIT_SHORT_SHA docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:prod
    - docker push docker.aws.ccit.ops.charter.com/corportal/agent-training-academy-ui:prod
  only:
    - release*
    - master
  when: manual
